# Site settings
title: Wheelhouse + Patchwork
email: hello@wheelhouse.io
description: > # this means to ignore newlines until "baseurl:"
  Use this courses to learn GitHub.
baseurl: "/patchwork" # the subpath of your site, e.g. /blog/
url: "http://wheelhouseio.github.io" # the base hostname & protocol for your site
twitter_username: WheelhouseIO
github_username:  wheelhouseio

# Build settings
sass:
  sass_dir: _sass
include: ['_statics']
kramdown:
  input: GFM